### ISSUE TITLE
Text cannot be rotated holding shift

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-paint#343] opened 2018-03-27 19:59 UTC
Try rotating text holding the shift button. 

![rotate-text](https://user-images.githubusercontent.com/654102/37991648-b7680a74-31d7-11e8-877b-a1a43868ac40.gif)

**Comment by fsih** [comment] 2018-04-03 14:25
Duplicate of https://github.com/LLK/scratch-paint/issues/332

**Closed as completed by fsih** 2018-04-03 14:25 UTC
Labels: bug
