### ISSUE TITLE
Uncaught TypeError: s is not a constructor

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratch-paint#256] opened 2018-01-17 15:49 UTC
Steps to repro:
1. Go to reshape tool on cat (the cat's mouth, in my case)
2. Drag one of the points a bit
3. Zoom in on the mouth
4. Try to drag a point again

Get the "oops something went wrong" page, with the following in the console:
```
Uncaught TypeError: s is not a constructor
    at t.value (https://llk.github.io/scratch-gui/lib.min.js:12:112704)
    at t.value (https://llk.github.io/scratch-gui/lib.min.js:126:883209)
    at Object.l [as onUpdateSvg] (https://llk.github.io/scratch-gui/lib.min.js:1:8358)
    at t.value (https://llk.github.io/scratch-gui/lib.min.js:51:101546)
    at e.l [as onUpdateSvg] (https://llk.github.io/scratch-gui/lib.min.js:46:364226)
    at e.value (https://llk.github.io/scratch-gui/lib.min.js:68:110424)
    at e.value (https://llk.github.io/scratch-gui/lib.min.js:51:50128)
    at t.value [as _onMouseUp] (https://llk.github.io/scratch-gui/lib.min.js:68:142702)
    at t.emit (https://llk.github.io/scratch-gui/lib.min.js:46:139046)
    at r (https://llk.github.io/scratch-gui/lib.min.js:46:312944)
    at t._handleMouseEvent (https://llk.github.io/scratch-gui/lib.min.js:46:313158)
    at initialize._handleMouseEvent (https://llk.github.io/scratch-gui/lib.min.js:46:306097)
    at HTMLDocument.m.(anonymous function) (https://llk.github.io/scratch-gui/lib.min.js:46:304862)
    at HTMLDocument.d (https://cdn.ravenjs.com/3.22.1/raven.min.js:2:4446)
```

**Comment by mewtaylor** [comment] 2018-01-17 15:53
Also Eric saw a similar error when he tried to use the paint brush tool on the cat:
![image](https://user-images.githubusercontent.com/1815772/35052070-aa33ba9a-fb74-11e7-8e1e-03eddf96fa5e.png)

**Comment by kerrtravers** [comment] 2018-01-17 15:58
I had the same issue, but only when I clicked somewhere else on the GUI after using the repro steps (the reshape tool was unresponsive at that point).

**Comment by cwillisf** [comment] 2018-01-17 16:01
@fsih suggested that my "oops" has a similar cause, even though I have a different call stack and different repro steps.

Steps:
- Start with default project, Cat sprite selected
- Click "Costumes"
- Add a new blank costume
- Select line tool
- Click & drag a line
  - Note that the line "sticks" to the cursor here
- Click the paintbrush tool

Call stack:
```
TypeError: e is undefined
Stack trace:
setParent@https://llk.github.io/scratch-gui/lib.min.js:46:180799
value@https://llk.github.io/scratch-gui/lib.min.js:51:72807
value@https://llk.github.io/scratch-gui/lib.min.js:51:70513
value@https://llk.github.io/scratch-gui/lib.min.js:51:70669
value@https://llk.github.io/scratch-gui/lib.min.js:61:120788
l@https://llk.github.io/scratch-gui/lib.min.js:46:364186
value@https://llk.github.io/scratch-gui/lib.min.js:61:120270
updateClassInstance@https://llk.github.io/scratch-gui/lib.min.js:92:22780
beginWork@https://llk.github.io/scratch-gui/lib.min.js:92:32197
o@https://llk.github.io/scratch-gui/lib.min.js:92:44327
i@https://llk.github.io/scratch-gui/lib.min.js:92:44648
u@https://llk.github.io/scratch-gui/lib.min.js:92:44886
v@https://llk.github.io/scratch-gui/lib.min.js:92:48429
E@https://llk.github.io/scratch-gui/lib.min.js:92:48166
batchedUpdates@https://llk.github.io/scratch-gui/lib.min.js:92:49595
$@https://llk.github.io/scratch-gui/lib.min.js:92:9667
Fe@https://llk.github.io/scratch-gui/lib.min.js:92:14119
d@https://cdn.ravenjs.com/3.22.1/raven.min.js:2:4444
```

**Comment by paulkaplan** [comment] 2018-01-17 16:05
Yup this is caused by https://github.com/LLK/scratch-vm/pull/897.

**Comment by thisandagain** [comment] 2018-01-18 13:49
Resolved in https://github.com/LLK/scratch-vm/pull/900

**Closed as completed by thisandagain** 2018-01-18 13:49 UTC
Labels: critical
