### ISSUE TITLE
A shape that was transparent in Paint appeared black on the stage

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#669] opened 2018-09-11 18:51 UTC
Mouth is filled with transparent in paint and looks black on stage. I never recolored the mouth. @fsih 
![image10](https://user-images.githubusercontent.com/1088291/45235290-6abebb00-b2a6-11e8-9ff3-ceaaf9a5cd4d.png)

**Comment by BryceLTaylor** [comment] 2018-10-23 21:27
I can't reproduce this.  @fsih Can you?  I'm not sure how you got into this state in the first place.  If you can't reproduce it we should just close it.

**Closed as completed** 2018-10-24 01:04 UTC
Labels: bug
