### ISSUE TITLE
Bitmap selection should trim transparent pixels

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#959] opened 2020-01-29 20:15 UTC
### Expected Behavior
Click-drag selections in bitmap mode should probably trim transparent pixels off the edges of the selection. This will make them work better with the new center snapping. (Could there be some use case we're not thinking of where keeping the transparent pixels in the selection is useful?)

### Actual Behavior
Selection does not trim transparent pixels

**Comment by rschamp** [comment] 2020-04-07 12:21
Closed in favor of #979, which is a dupe of this one with repro steps

**Closed as completed by rschamp** 2020-04-07 12:21 UTC
