### ISSUE TITLE
Zoom controls are reverse

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-paint#123] opened 2017-10-27 18:36 UTC
Zoom controls are inverted from 2.0.
<img width="280" alt="screen shot 2017-10-27 at 2 35 11 pm" src="https://user-images.githubusercontent.com/3409578/32119701-119598de-bb24-11e7-94a5-5c0b6ead3391.png">

We should match 2.0's layout: Zoom out, Reset, Zoom in

**Comment by jwzimmer-zz** [comment] 2017-10-27 20:31
Closing https://github.com/LLK/scratch-paint/issues/127 as dupe of this issue.

From @fsih:
> The zoom buttons are in a different order on Scratch 3.0 paint editor vs 2.0 editor
> They are also in a different order in scratch blocks
> Issue from ericr/thisandagain/paulkaplan/carljbowman

**Closed as completed** 2017-10-30 12:53 UTC
Labels: bug, has-patch
