### ISSUE TITLE
Zoom controls reversed?

### ISSUE THREAD

**Issue by griffpatch** [LLK/scratch-paint#162] opened 2017-10-30 08:27 UTC
I would expect the zoom in to be on the right side, and the zoom out to be on the left?
Great to see the zoom feature though - excellent :) I wonder if the size of the painting region could be enlarged when space is available?

**Comment by towerofnix** [comment] 2017-10-30 11:56
>I would expect the zoom in to be on the right side, and the zoom out to be on the left?

Probably a duplicate of #123.

>I wonder if the size of the painting region could be enlarged when space is available?

As in, resizing the editor itself, to fill available space in the costumes tab? That would be a welcomed change!

**Comment by thisandagain** [comment] 2017-10-30 12:11
Tracking zoom control reversal in #123 (has patch)
Tracking workspace size issue in #146

**Closed as completed by thisandagain** 2017-10-30 12:11 UTC
