### ISSUE TITLE
Bitmap brush tool causes sprites to disappear from stage on Safari

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-paint#419] opened 2018-05-02 21:27 UTC
### Expected Behavior

Drawing on a sprite that has been converted to bitmap should make visible changes to the sprite on the stage.

### Actual Behavior

If you convert a sprite to bitmap and draw on it with the paintbrush the sprite disappears on the stage if it is on that costume.

![safaridrawundersprite2](https://user-images.githubusercontent.com/1088291/39491889-c7a05af0-4d5b-11e8-9eaf-1f8d72760745.gif)

If you click "Convert to Vector" the cat and the line appear on the stage.

Alternatively, if you switch to a different costume and then back to the first one, you can draw on it again and it will appear.  I think that that has to do with it being in vector mode again.

There is a related issue where the thumbnail for the costume also goes blank: LLK/scratch-gui#1936 

### Steps to Reproduce

Create a new project in Safari
Open the costumes tab
Click "Convert to Bitmap"
With the brush tool draw a line
Note how the cat and line disappear from the stage

### Operating System and Browser

Safari Version 11.1 (13605.1.33.1.2) on Mac OS 10.13.4

---
Moved from LLK/scratch-gui#1933
/cc @BryceLTaylor

**Comment by fsih** [comment] 2018-05-23 22:12
@BryceLTaylor I haven't been able to repro this. Were you able to do it consistently?

**Comment by BryceLTaylor** [comment] 2018-05-24 13:43
I can't now in exactly the same way shown above.  It's possible it was fixed in some of the other changes that have been made.

I am, however, seeing a related issue, where if I turn it back to vector it disappears from the stage.

![converttovector](https://user-images.githubusercontent.com/1088291/40489247-ab2824a6-5f36-11e8-94a3-45d5fc31011a.gif)

I don't think that's in another issue yet.

**Comment by BryceLTaylor** [comment] 2018-07-10 14:10
Duplicate of https://github.com/LLK/scratch-paint/issues/418

**Closed as completed by BryceLTaylor** 2018-07-10 14:10 UTC
Labels: bug, safari
