### ISSUE TITLE
Make lines the right thickness

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#140] opened 2017-10-27 19:53 UTC
When you're zoomed in, line thickness is not accurately represented. Line thickness doesn't change with zoom.

**Comment by jwzimmer-zz** [comment] 2017-10-27 19:55
Closing https://github.com/LLK/scratch-paint/issues/139 as a dupe of this issue:

I didn't change the line width when I was working on this sprite, but you can see how the apparent line width changed over time as I zoomed in & out repeatedly:
<img width="464" alt="screen shot 2017-10-27 at 3 01 45 pm" src="https://user-images.githubusercontent.com/1320456/32122597-e4e40c0c-bb2e-11e7-8e03-bd2f6574b25e.png">
<img width="476" alt="screen shot 2017-10-27 at 3 52 30 pm" src="https://user-images.githubusercontent.com/1320456/32122595-e4cb63b4-bb2e-11e7-863a-c055a481c58d.png">
<img width="432" alt="screen shot 2017-10-27 at 3 52 15 pm" src="https://user-images.githubusercontent.com/1320456/32122596-e4d61322-bb2e-11e7-8ae8-b6e1e6f9d9be.png">

**Comment by paulkaplan** [comment] 2017-10-29 19:06
I can't seem to get a consistent repro of this, but I know it happened to me at the playtest. Can you lay it out step-by-step?

**Comment by jwzimmer-zz** [comment] 2017-10-30 17:28
@paulkaplan, I was trying to repro this, and it's not clear to me what the steps are yet (sorry) but I did see it again. I wonder if it has to do with that I'm both setting the zoom for Chrome & for the editor (I have to zoom out in Chrome in order to see the zoom buttons in the editor)?
<img width="1196" alt="screen shot 2017-10-30 at 1 11 16 pm" src="https://user-images.githubusercontent.com/1320456/32185254-069201c2-bd75-11e7-86d1-c84533523718.png">

**Comment by fsih** [comment] 2017-11-07 16:48
I figured out the repro

1. Select and scale anything
2. That thing now always has the same stroke widths when zoomed in

**Closed as completed** 2017-11-08 20:59 UTC
