### ISSUE TITLE
On iPad mini, tapping and holding a scroll bar causes a gray overlay to appear over the left half of the screen

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-paint#613] opened 2018-08-20 18:37 UTC
On iPad mini, tapping and holding a scroll bar causes a gray overlay to appear over the left half of the screen. Trying to drag them causes the entire page to scroll slightly

From @rschamp smoke test 8/17/18
### Operating System and Browser
iPad mini

**Comment by picklesrus** [comment] 2018-10-05 20:39
closing as duplicate of https://github.com/LLK/scratch-paint/issues/703

**Closed as completed by picklesrus** 2018-10-05 20:39 UTC
Labels: bug, needs triage, ios
