### ISSUE TITLE
Selecting in bitmap should not include blank pixels in the selected area

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-paint#979] opened 2020-02-10 20:04 UTC
### Expected Behavior

In bitmap mode, if you select an area around an image and there are many empty on the edge of the bounding box, the bounding box should shrink so that it just fits around the actual pixels.

### Actual Behavior

Currently it keeps the selected bounding box at the larger size.  With the addition of the centering tool, this will put the "center" of the shape in relation to the bounding box and not the selected shape.

### Steps to Reproduce

Create a project
Open the costume editor
Convert to Bitmap
Choose the selection tool
Select an area larger than the cat
Note: the bounding box for the selected area is whatever you had chosen and doesn't change shape to fit the non-transparent pixels in the selected area
Note: with the Centering tool the "center of the cat" will not be in the actual center of the cat if you selected a shape that is much bigger than the cat.

### Operating System and Browser

Mac Chrome

**Comment by adroitwhiz** [comment] 2020-02-10 20:05
Isn't this a duplicate of #959?

**Closed as completed** 2020-05-11 17:08 UTC
Labels: enhancement, priority 3
